name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - myfirstbranch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          base_uri: http://eu.ast-cloud.com
          client_id: ${{ secrets.CLIENT_ID }}
          secret: ${{ secrets.SECRET }}
